apiVersion: v1
kind: Namespace
metadata:
  name: background-jobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: background-processor
  namespace: background-jobs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-processor
  namespace: background-jobs
  labels:
    app: background-processor
    version: v0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background-processor
      version: v0.1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: background-processor
        version: v0.1
    spec:
      containers:
      - name: background-processor
        image: xeviknal/background-processor:v0.1
        imagePullPolicy: IfNotPresent
      serviceAccountName: background-processor
      serviceAccount: background-processor
